/**
 * Greenville robots.txt — auto-generated by Next.js.
 * Spec ref: SEO-003
 */

import { MetadataRoute } from "next";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: "*",
      allow: "/",
      disallow: ["/api/", "/thank-you"],
    },
    sitemap: "https://sellgreenvillehomefast.com/sitemap.xml",
  };
}
